version: '3'

services:
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    environment:
      - PORT=3000
      - AMQP_URL=amqps://pzecprke:u5A6kwEa91dmGlyiuVIomx_8hLW_yXrt@jackal.rmq.cloudamqp.com/pzecprke
      - DOJO_API_TOKEN=MDBiNWFlMTBlYzgyNGVjM2JmNjQyOGEzOGM4ODFhYTQ6NWRlZDc3ZjIwZDM0NDc5MjliYmE2Y2RiYWM1ZDc1YjA=
    networks:
      - app-network
    links:
      - rabbitmq
    ports:
      - "3000:3000"

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    environment:
      - PORT=3000
      - AMQP_URL=amqps://pzecprke:u5A6kwEa91dmGlyiuVIomx_8hLW_yXrt@jackal.rmq.cloudamqp.com/pzecprke
      - DOJO_API_TOKEN=MDBiNWFlMTBlYzgyNGVjM2JmNjQyOGEzOGM4ODFhYTQ6NWRlZDc3ZjIwZDM0NDc5MjliYmE2Y2RiYWM1ZDc1YjA=
    networks:
      - app-network
    links:
      - rabbitmq
    ports:
      - "3001:3000"

  rabbitmq:
    image: rabbitmq:3.8-alpine
    networks:
      - app-network

networks:
  app-network:
    driver: bridge