version: '3'

services:
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    networks:
      - app-network
    links:
      - rabbitmq

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    networks:
      - app-network
    links:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.7
    networks:
      - app-network

networks:
  app-network:
    driver: bridge